version: "3"

services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks: 
      - iceberg
    ports:
      - 19120:19120
  # MinIO Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - iceberg
    ports:
      - 9000:9000
      - 9090:9090
    command: ["server", "/data", "--console-address", ":9090", "/mnt/data"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - type: bind
        source: ${LAKEHOUSE_PATH}/data/minio
        target: /mnt/data
      - type: bind
        source: ${LAKEHOUSE_PATH}/etc/default/minio
        target: /etc/config.env
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    networks:
      - iceberg
  prefect:
    image: prefecthq/prefect:3.1.16.dev3-python3.11-conda
    restart: always
    volumes:
      - prefect-data:/data
      - .:/app
    environment:
      PREFECT_HOME: /data
    command: prefect server start --host 0.0.0.0
    container_name: prefect
    ports:
      - 4200:4200
    networks:
      - iceberg
networks:
  iceberg:
volumes:
  prefect-data: {}


# Add qdrant, ollama, open-webui 
